CONNECT 'jdbc:derby://localhost:1527/databases/AddressBook;user=db_user;password=db_user;create=true';
CONNECT 'jdbc:derby://localhost:1527/databases/AddressBook;user=db_user;password=db_user';

CREATE TABLE CONTACTS (ID_CONTACTS INT PRIMARY KEY, FIRSTNAME VARCHAR(30) NOT NULL, LASTNAME VARCHAR(30) NOT NULL, MIDLENAME VARCHAR(30) NOT NULL, TELEPHONE INT UNIQUE NOT NULL);

CREATE TABLE PHONENUMBERS (ID_PHONENUMBER INT PRIMARY KEY, PHONENUMBER VARCHAR(12) UNIQUE NOT NULL);
