CONNECT 'jdbc:derby://localhost:1527/databases/Classrooms;user=db_user;password=db_user;create=true';
CONNECT 'jdbc:derby://localhost:1527/databases/Classrooms;user=db_user;password=db_user';

CREATE TABLE CLASSROOM (ID_CLASSROOM INT PRIMARY KEY, BUILDING VARCHAR(30) NOT NULL, CLASSROOM_NUMBER VARCHAR(4) NOT NULL, CLASSROOM_NAME VARCHAR(30) NOT NULL, SQUARE INT NOT NULL);

CREATE TABLE RESPONSIBLE (ID_RESPONSIBLE INT PRIMARY KEY, SURNAME VARCHAR(30) NOT NULL, NAME VARCHAR(30) NOT NULL, PATRONYMIC VARCHAR(30) NOT NULL, POST VARCHAR(30) NOT NULL, TELEPHONE INT UNIQUE NOT NULL, AGE INT NOT NULL)
